---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-db
spec:
  template:
    metadata:
      labels:
        app: aqua-db
      name: aqua-db
    spec:
      serviceAccount: aqua-sa
      imagePullSecrets:
        - name: aqua-registry
      containers:
      - name: aqua-db
        image: registry.aquasec.com/database:4.6
        securityContext:
          privileged: true
        env:
          - name: postgres-password
            valueFrom:
              secretKeyRef:
                key: password
                name: aqua-db
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: aquadb-data-mount
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
      volumes:
        - name: aquadb-data-mount
          persistentVolumeClaim:
            claimName: aquadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: aqua-db
  labels:
    app: aqua-db
spec:
  type: ClusterIP
  selector:
    app: aqua-db
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: aqua-web
  labels:
    app: aqua-web
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
      name: aqua-web-ssl
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: aqua-web
  selector:
    app: aqua-web
  type: LoadBalancer